// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.0
// source: aiserver/v1/available_models_mvp.proto

package aiserverv1

import (
	v1 "github.com/router-for-me/CLIProxyAPI/v7/internal/cursor/proto/agent/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvailableModelsRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	IsNightly                bool                   `protobuf:"varint,1,opt,name=is_nightly,json=isNightly,proto3" json:"is_nightly,omitempty"`
	IncludeLongContextModels bool                   `protobuf:"varint,2,opt,name=include_long_context_models,json=includeLongContextModels,proto3" json:"include_long_context_models,omitempty"`
	ExcludeMaxNamedModels    bool                   `protobuf:"varint,3,opt,name=exclude_max_named_models,json=excludeMaxNamedModels,proto3" json:"exclude_max_named_models,omitempty"`
	AdditionalModelNames     []string               `protobuf:"bytes,4,rep,name=additional_model_names,json=additionalModelNames,proto3" json:"additional_model_names,omitempty"`
	UseModelParameters       *bool                  `protobuf:"varint,5,opt,name=use_model_parameters,json=useModelParameters,proto3,oneof" json:"use_model_parameters,omitempty"`
	UseReactModelPicker      *bool                  `protobuf:"varint,11,opt,name=use_react_model_picker,json=useReactModelPicker,proto3,oneof" json:"use_react_model_picker,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AvailableModelsRequest) Reset() {
	*x = AvailableModelsRequest{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableModelsRequest) ProtoMessage() {}

func (x *AvailableModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableModelsRequest.ProtoReflect.Descriptor instead.
func (*AvailableModelsRequest) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableModelsRequest) GetIsNightly() bool {
	if x != nil {
		return x.IsNightly
	}
	return false
}

func (x *AvailableModelsRequest) GetIncludeLongContextModels() bool {
	if x != nil {
		return x.IncludeLongContextModels
	}
	return false
}

func (x *AvailableModelsRequest) GetExcludeMaxNamedModels() bool {
	if x != nil {
		return x.ExcludeMaxNamedModels
	}
	return false
}

func (x *AvailableModelsRequest) GetAdditionalModelNames() []string {
	if x != nil {
		return x.AdditionalModelNames
	}
	return nil
}

func (x *AvailableModelsRequest) GetUseModelParameters() bool {
	if x != nil && x.UseModelParameters != nil {
		return *x.UseModelParameters
	}
	return false
}

func (x *AvailableModelsRequest) GetUseReactModelPicker() bool {
	if x != nil && x.UseReactModelPicker != nil {
		return *x.UseReactModelPicker
	}
	return false
}

type ModelParameterDefinition struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Id            string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParameterType *ModelParameterDefinition_ModelParameterType `protobuf:"bytes,4,opt,name=parameter_type,json=parameterType,proto3" json:"parameter_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelParameterDefinition) Reset() {
	*x = ModelParameterDefinition{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelParameterDefinition) ProtoMessage() {}

func (x *ModelParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelParameterDefinition.ProtoReflect.Descriptor instead.
func (*ModelParameterDefinition) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{1}
}

func (x *ModelParameterDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelParameterDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelParameterDefinition) GetParameterType() *ModelParameterDefinition_ModelParameterType {
	if x != nil {
		return x.ParameterType
	}
	return nil
}

type AvailableModelsResponse struct {
	state              protoimpl.MessageState                    `protogen:"open.v1"`
	ModelNames         []string                                  `protobuf:"bytes,1,rep,name=model_names,json=modelNames,proto3" json:"model_names,omitempty"`
	Models             []*AvailableModelsResponse_AvailableModel `protobuf:"bytes,2,rep,name=models,proto3" json:"models,omitempty"`
	UseModelParameters bool                                      `protobuf:"varint,11,opt,name=use_model_parameters,json=useModelParameters,proto3" json:"use_model_parameters,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AvailableModelsResponse) Reset() {
	*x = AvailableModelsResponse{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableModelsResponse) ProtoMessage() {}

func (x *AvailableModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableModelsResponse.ProtoReflect.Descriptor instead.
func (*AvailableModelsResponse) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{2}
}

func (x *AvailableModelsResponse) GetModelNames() []string {
	if x != nil {
		return x.ModelNames
	}
	return nil
}

func (x *AvailableModelsResponse) GetModels() []*AvailableModelsResponse_AvailableModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AvailableModelsResponse) GetUseModelParameters() bool {
	if x != nil {
		return x.UseModelParameters
	}
	return false
}

type ModelParameterDefinition_ModelParameterType struct {
	state            protoimpl.MessageState                               `protogen:"open.v1"`
	BooleanParameter *ModelParameterDefinition_BooleanParameterDefinition `protobuf:"bytes,1,opt,name=boolean_parameter,json=booleanParameter,proto3,oneof" json:"boolean_parameter,omitempty"`
	EnumParameter    *ModelParameterDefinition_EnumParameterDefinition    `protobuf:"bytes,2,opt,name=enum_parameter,json=enumParameter,proto3,oneof" json:"enum_parameter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ModelParameterDefinition_ModelParameterType) Reset() {
	*x = ModelParameterDefinition_ModelParameterType{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelParameterDefinition_ModelParameterType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelParameterDefinition_ModelParameterType) ProtoMessage() {}

func (x *ModelParameterDefinition_ModelParameterType) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelParameterDefinition_ModelParameterType.ProtoReflect.Descriptor instead.
func (*ModelParameterDefinition_ModelParameterType) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ModelParameterDefinition_ModelParameterType) GetBooleanParameter() *ModelParameterDefinition_BooleanParameterDefinition {
	if x != nil {
		return x.BooleanParameter
	}
	return nil
}

func (x *ModelParameterDefinition_ModelParameterType) GetEnumParameter() *ModelParameterDefinition_EnumParameterDefinition {
	if x != nil {
		return x.EnumParameter
	}
	return nil
}

type ModelParameterDefinition_BooleanParameterDefinition struct {
	state         protoimpl.MessageState                                                       `protogen:"open.v1"`
	Values        []*ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelParameterDefinition_BooleanParameterDefinition) Reset() {
	*x = ModelParameterDefinition_BooleanParameterDefinition{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelParameterDefinition_BooleanParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelParameterDefinition_BooleanParameterDefinition) ProtoMessage() {}

func (x *ModelParameterDefinition_BooleanParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelParameterDefinition_BooleanParameterDefinition.ProtoReflect.Descriptor instead.
func (*ModelParameterDefinition_BooleanParameterDefinition) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ModelParameterDefinition_BooleanParameterDefinition) GetValues() []*ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type ModelParameterDefinition_EnumParameterDefinition struct {
	state         protoimpl.MessageState                                                 `protogen:"open.v1"`
	Values        []*ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelParameterDefinition_EnumParameterDefinition) Reset() {
	*x = ModelParameterDefinition_EnumParameterDefinition{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelParameterDefinition_EnumParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelParameterDefinition_EnumParameterDefinition) ProtoMessage() {}

func (x *ModelParameterDefinition_EnumParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelParameterDefinition_EnumParameterDefinition.ProtoReflect.Descriptor instead.
func (*ModelParameterDefinition_EnumParameterDefinition) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{1, 2}
}

func (x *ModelParameterDefinition_EnumParameterDefinition) GetValues() []*ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue) Reset() {
	*x = ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue) ProtoMessage() {}

func (x *ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue.ProtoReflect.Descriptor instead.
func (*ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{1, 1, 0}
}

func (x *ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue) Reset() {
	*x = ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue) ProtoMessage() {}

func (x *ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue.ProtoReflect.Descriptor instead.
func (*ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{1, 2, 0}
}

func (x *ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AvailableModelsResponse_AvailableModel struct {
	state                protoimpl.MessageState                        `protogen:"open.v1"`
	Name                 string                                        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SupportsThinking     *bool                                         `protobuf:"varint,9,opt,name=supports_thinking,json=supportsThinking,proto3,oneof" json:"supports_thinking,omitempty"`
	SupportsImages       *bool                                         `protobuf:"varint,10,opt,name=supports_images,json=supportsImages,proto3,oneof" json:"supports_images,omitempty"`
	ClientDisplayName    *string                                       `protobuf:"bytes,17,opt,name=client_display_name,json=clientDisplayName,proto3,oneof" json:"client_display_name,omitempty"`
	ServerModelName      *string                                       `protobuf:"bytes,18,opt,name=server_model_name,json=serverModelName,proto3,oneof" json:"server_model_name,omitempty"`
	SupportsNonMaxMode   *bool                                         `protobuf:"varint,19,opt,name=supports_non_max_mode,json=supportsNonMaxMode,proto3,oneof" json:"supports_non_max_mode,omitempty"`
	ParameterDefinitions []*ModelParameterDefinition                   `protobuf:"bytes,29,rep,name=parameter_definitions,json=parameterDefinitions,proto3" json:"parameter_definitions,omitempty"`
	Variants             []*AvailableModelsResponse_ModelVariantConfig `protobuf:"bytes,30,rep,name=variants,proto3" json:"variants,omitempty"`
	IdAliases            []string                                      `protobuf:"bytes,37,rep,name=id_aliases,json=idAliases,proto3" json:"id_aliases,omitempty"`
	ContextTokenLimit    *int32                                        `protobuf:"varint,15,opt,name=context_token_limit,json=contextTokenLimit,proto3,oneof" json:"context_token_limit,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AvailableModelsResponse_AvailableModel) Reset() {
	*x = AvailableModelsResponse_AvailableModel{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableModelsResponse_AvailableModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableModelsResponse_AvailableModel) ProtoMessage() {}

func (x *AvailableModelsResponse_AvailableModel) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableModelsResponse_AvailableModel.ProtoReflect.Descriptor instead.
func (*AvailableModelsResponse_AvailableModel) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AvailableModelsResponse_AvailableModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvailableModelsResponse_AvailableModel) GetSupportsThinking() bool {
	if x != nil && x.SupportsThinking != nil {
		return *x.SupportsThinking
	}
	return false
}

func (x *AvailableModelsResponse_AvailableModel) GetSupportsImages() bool {
	if x != nil && x.SupportsImages != nil {
		return *x.SupportsImages
	}
	return false
}

func (x *AvailableModelsResponse_AvailableModel) GetClientDisplayName() string {
	if x != nil && x.ClientDisplayName != nil {
		return *x.ClientDisplayName
	}
	return ""
}

func (x *AvailableModelsResponse_AvailableModel) GetServerModelName() string {
	if x != nil && x.ServerModelName != nil {
		return *x.ServerModelName
	}
	return ""
}

func (x *AvailableModelsResponse_AvailableModel) GetSupportsNonMaxMode() bool {
	if x != nil && x.SupportsNonMaxMode != nil {
		return *x.SupportsNonMaxMode
	}
	return false
}

func (x *AvailableModelsResponse_AvailableModel) GetParameterDefinitions() []*ModelParameterDefinition {
	if x != nil {
		return x.ParameterDefinitions
	}
	return nil
}

func (x *AvailableModelsResponse_AvailableModel) GetVariants() []*AvailableModelsResponse_ModelVariantConfig {
	if x != nil {
		return x.Variants
	}
	return nil
}

func (x *AvailableModelsResponse_AvailableModel) GetIdAliases() []string {
	if x != nil {
		return x.IdAliases
	}
	return nil
}

func (x *AvailableModelsResponse_AvailableModel) GetContextTokenLimit() int32 {
	if x != nil && x.ContextTokenLimit != nil {
		return *x.ContextTokenLimit
	}
	return 0
}

type AvailableModelsResponse_ModelVariantConfig struct {
	state                       protoimpl.MessageState                   `protogen:"open.v1"`
	ParameterValues             []*v1.RequestedModel_ModelParameterValue `protobuf:"bytes,1,rep,name=parameter_values,json=parameterValues,proto3" json:"parameter_values,omitempty"`
	DisplayName                 string                                   `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IsMaxMode                   bool                                     `protobuf:"varint,3,opt,name=is_max_mode,json=isMaxMode,proto3" json:"is_max_mode,omitempty"`
	IsDefaultNonMaxConfig       *bool                                    `protobuf:"varint,5,opt,name=is_default_non_max_config,json=isDefaultNonMaxConfig,proto3,oneof" json:"is_default_non_max_config,omitempty"`
	VariantStringRepresentation *string                                  `protobuf:"bytes,9,opt,name=variant_string_representation,json=variantStringRepresentation,proto3,oneof" json:"variant_string_representation,omitempty"`
	LegacySlug                  *string                                  `protobuf:"bytes,11,opt,name=legacy_slug,json=legacySlug,proto3,oneof" json:"legacy_slug,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AvailableModelsResponse_ModelVariantConfig) Reset() {
	*x = AvailableModelsResponse_ModelVariantConfig{}
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableModelsResponse_ModelVariantConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableModelsResponse_ModelVariantConfig) ProtoMessage() {}

func (x *AvailableModelsResponse_ModelVariantConfig) ProtoReflect() protoreflect.Message {
	mi := &file_aiserver_v1_available_models_mvp_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableModelsResponse_ModelVariantConfig.ProtoReflect.Descriptor instead.
func (*AvailableModelsResponse_ModelVariantConfig) Descriptor() ([]byte, []int) {
	return file_aiserver_v1_available_models_mvp_proto_rawDescGZIP(), []int{2, 1}
}

func (x *AvailableModelsResponse_ModelVariantConfig) GetParameterValues() []*v1.RequestedModel_ModelParameterValue {
	if x != nil {
		return x.ParameterValues
	}
	return nil
}

func (x *AvailableModelsResponse_ModelVariantConfig) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AvailableModelsResponse_ModelVariantConfig) GetIsMaxMode() bool {
	if x != nil {
		return x.IsMaxMode
	}
	return false
}

func (x *AvailableModelsResponse_ModelVariantConfig) GetIsDefaultNonMaxConfig() bool {
	if x != nil && x.IsDefaultNonMaxConfig != nil {
		return *x.IsDefaultNonMaxConfig
	}
	return false
}

func (x *AvailableModelsResponse_ModelVariantConfig) GetVariantStringRepresentation() string {
	if x != nil && x.VariantStringRepresentation != nil {
		return *x.VariantStringRepresentation
	}
	return ""
}

func (x *AvailableModelsResponse_ModelVariantConfig) GetLegacySlug() string {
	if x != nil && x.LegacySlug != nil {
		return *x.LegacySlug
	}
	return ""
}

var File_aiserver_v1_available_models_mvp_proto protoreflect.FileDescriptor

const file_aiserver_v1_available_models_mvp_proto_rawDesc = "" +
	"\n" +
	"&aiserver/v1/available_models_mvp.proto\x12\vaiserver.v1\x1a\x18agent/v1/agent_mvp.proto\"\x8a\x03\n" +
	"\x16AvailableModelsRequest\x12\x1d\n" +
	"\n" +
	"is_nightly\x18\x01 \x01(\bR\tisNightly\x12=\n" +
	"\x1binclude_long_context_models\x18\x02 \x01(\bR\x18includeLongContextModels\x127\n" +
	"\x18exclude_max_named_models\x18\x03 \x01(\bR\x15excludeMaxNamedModels\x124\n" +
	"\x16additional_model_names\x18\x04 \x03(\tR\x14additionalModelNames\x125\n" +
	"\x14use_model_parameters\x18\x05 \x01(\bH\x00R\x12useModelParameters\x88\x01\x01\x128\n" +
	"\x16use_react_model_picker\x18\v \x01(\bH\x01R\x13useReactModelPicker\x88\x01\x01B\x17\n" +
	"\x15_use_model_parametersB\x19\n" +
	"\x17_use_react_model_picker\"\xae\x06\n" +
	"\x18ModelParameterDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12_\n" +
	"\x0eparameter_type\x18\x04 \x01(\v28.aiserver.v1.ModelParameterDefinition.ModelParameterTypeR\rparameterType\x1a\x9c\x02\n" +
	"\x12ModelParameterType\x12r\n" +
	"\x11boolean_parameter\x18\x01 \x01(\v2@.aiserver.v1.ModelParameterDefinition.BooleanParameterDefinitionH\x00R\x10booleanParameter\x88\x01\x01\x12i\n" +
	"\x0eenum_parameter\x18\x02 \x01(\v2=.aiserver.v1.ModelParameterDefinition.EnumParameterDefinitionH\x01R\renumParameter\x88\x01\x01B\x14\n" +
	"\x12_boolean_parameterB\x11\n" +
	"\x0f_enum_parameter\x1a\xbb\x01\n" +
	"\x1aBooleanParameterDefinition\x12n\n" +
	"\x06values\x18\x01 \x03(\v2V.aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition.BooleanParameterValueR\x06values\x1a-\n" +
	"\x15BooleanParameterValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a\xaf\x01\n" +
	"\x17EnumParameterDefinition\x12h\n" +
	"\x06values\x18\x01 \x03(\v2P.aiserver.v1.ModelParameterDefinition.EnumParameterDefinition.EnumParameterValueR\x06values\x1a*\n" +
	"\x12EnumParameterValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x9e\n" +
	"\n" +
	"\x17AvailableModelsResponse\x12\x1f\n" +
	"\vmodel_names\x18\x01 \x03(\tR\n" +
	"modelNames\x12K\n" +
	"\x06models\x18\x02 \x03(\v23.aiserver.v1.AvailableModelsResponse.AvailableModelR\x06models\x120\n" +
	"\x14use_model_parameters\x18\v \x01(\bR\x12useModelParameters\x1a\xb1\x05\n" +
	"\x0eAvailableModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x11supports_thinking\x18\t \x01(\bH\x00R\x10supportsThinking\x88\x01\x01\x12,\n" +
	"\x0fsupports_images\x18\n" +
	" \x01(\bH\x01R\x0esupportsImages\x88\x01\x01\x123\n" +
	"\x13client_display_name\x18\x11 \x01(\tH\x02R\x11clientDisplayName\x88\x01\x01\x12/\n" +
	"\x11server_model_name\x18\x12 \x01(\tH\x03R\x0fserverModelName\x88\x01\x01\x126\n" +
	"\x15supports_non_max_mode\x18\x13 \x01(\bH\x04R\x12supportsNonMaxMode\x88\x01\x01\x12Z\n" +
	"\x15parameter_definitions\x18\x1d \x03(\v2%.aiserver.v1.ModelParameterDefinitionR\x14parameterDefinitions\x12S\n" +
	"\bvariants\x18\x1e \x03(\v27.aiserver.v1.AvailableModelsResponse.ModelVariantConfigR\bvariants\x12\x1d\n" +
	"\n" +
	"id_aliases\x18% \x03(\tR\tidAliases\x123\n" +
	"\x13context_token_limit\x18\x0f \x01(\x05H\x05R\x11contextTokenLimit\x88\x01\x01B\x14\n" +
	"\x12_supports_thinkingB\x12\n" +
	"\x10_supports_imagesB\x16\n" +
	"\x14_client_display_nameB\x14\n" +
	"\x12_server_model_nameB\x18\n" +
	"\x16_supports_non_max_modeB\x16\n" +
	"\x14_context_token_limit\x1a\xae\x03\n" +
	"\x12ModelVariantConfig\x12W\n" +
	"\x10parameter_values\x18\x01 \x03(\v2,.agent.v1.RequestedModel.ModelParameterValueR\x0fparameterValues\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1e\n" +
	"\vis_max_mode\x18\x03 \x01(\bR\tisMaxMode\x12=\n" +
	"\x19is_default_non_max_config\x18\x05 \x01(\bH\x00R\x15isDefaultNonMaxConfig\x88\x01\x01\x12G\n" +
	"\x1dvariant_string_representation\x18\t \x01(\tH\x01R\x1bvariantStringRepresentation\x88\x01\x01\x12$\n" +
	"\vlegacy_slug\x18\v \x01(\tH\x02R\n" +
	"legacySlug\x88\x01\x01B\x1c\n" +
	"\x1a_is_default_non_max_configB \n" +
	"\x1e_variant_string_representationB\x0e\n" +
	"\f_legacy_slugBVZTgithub.com/router-for-me/CLIProxyAPI/v7/internal/cursor/proto/aiserver/v1;aiserverv1b\x06proto3"

var (
	file_aiserver_v1_available_models_mvp_proto_rawDescOnce sync.Once
	file_aiserver_v1_available_models_mvp_proto_rawDescData []byte
)

func file_aiserver_v1_available_models_mvp_proto_rawDescGZIP() []byte {
	file_aiserver_v1_available_models_mvp_proto_rawDescOnce.Do(func() {
		file_aiserver_v1_available_models_mvp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aiserver_v1_available_models_mvp_proto_rawDesc), len(file_aiserver_v1_available_models_mvp_proto_rawDesc)))
	})
	return file_aiserver_v1_available_models_mvp_proto_rawDescData
}

var file_aiserver_v1_available_models_mvp_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aiserver_v1_available_models_mvp_proto_goTypes = []any{
	(*AvailableModelsRequest)(nil),                                                    // 0: aiserver.v1.AvailableModelsRequest
	(*ModelParameterDefinition)(nil),                                                  // 1: aiserver.v1.ModelParameterDefinition
	(*AvailableModelsResponse)(nil),                                                   // 2: aiserver.v1.AvailableModelsResponse
	(*ModelParameterDefinition_ModelParameterType)(nil),                               // 3: aiserver.v1.ModelParameterDefinition.ModelParameterType
	(*ModelParameterDefinition_BooleanParameterDefinition)(nil),                       // 4: aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition
	(*ModelParameterDefinition_EnumParameterDefinition)(nil),                          // 5: aiserver.v1.ModelParameterDefinition.EnumParameterDefinition
	(*ModelParameterDefinition_BooleanParameterDefinition_BooleanParameterValue)(nil), // 6: aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition.BooleanParameterValue
	(*ModelParameterDefinition_EnumParameterDefinition_EnumParameterValue)(nil),       // 7: aiserver.v1.ModelParameterDefinition.EnumParameterDefinition.EnumParameterValue
	(*AvailableModelsResponse_AvailableModel)(nil),                                    // 8: aiserver.v1.AvailableModelsResponse.AvailableModel
	(*AvailableModelsResponse_ModelVariantConfig)(nil),                                // 9: aiserver.v1.AvailableModelsResponse.ModelVariantConfig
	(*v1.RequestedModel_ModelParameterValue)(nil),                                     // 10: agent.v1.RequestedModel.ModelParameterValue
}
var file_aiserver_v1_available_models_mvp_proto_depIdxs = []int32{
	3,  // 0: aiserver.v1.ModelParameterDefinition.parameter_type:type_name -> aiserver.v1.ModelParameterDefinition.ModelParameterType
	8,  // 1: aiserver.v1.AvailableModelsResponse.models:type_name -> aiserver.v1.AvailableModelsResponse.AvailableModel
	4,  // 2: aiserver.v1.ModelParameterDefinition.ModelParameterType.boolean_parameter:type_name -> aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition
	5,  // 3: aiserver.v1.ModelParameterDefinition.ModelParameterType.enum_parameter:type_name -> aiserver.v1.ModelParameterDefinition.EnumParameterDefinition
	6,  // 4: aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition.values:type_name -> aiserver.v1.ModelParameterDefinition.BooleanParameterDefinition.BooleanParameterValue
	7,  // 5: aiserver.v1.ModelParameterDefinition.EnumParameterDefinition.values:type_name -> aiserver.v1.ModelParameterDefinition.EnumParameterDefinition.EnumParameterValue
	1,  // 6: aiserver.v1.AvailableModelsResponse.AvailableModel.parameter_definitions:type_name -> aiserver.v1.ModelParameterDefinition
	9,  // 7: aiserver.v1.AvailableModelsResponse.AvailableModel.variants:type_name -> aiserver.v1.AvailableModelsResponse.ModelVariantConfig
	10, // 8: aiserver.v1.AvailableModelsResponse.ModelVariantConfig.parameter_values:type_name -> agent.v1.RequestedModel.ModelParameterValue
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_aiserver_v1_available_models_mvp_proto_init() }
func file_aiserver_v1_available_models_mvp_proto_init() {
	if File_aiserver_v1_available_models_mvp_proto != nil {
		return
	}
	file_aiserver_v1_available_models_mvp_proto_msgTypes[0].OneofWrappers = []any{}
	file_aiserver_v1_available_models_mvp_proto_msgTypes[3].OneofWrappers = []any{}
	file_aiserver_v1_available_models_mvp_proto_msgTypes[8].OneofWrappers = []any{}
	file_aiserver_v1_available_models_mvp_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aiserver_v1_available_models_mvp_proto_rawDesc), len(file_aiserver_v1_available_models_mvp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aiserver_v1_available_models_mvp_proto_goTypes,
		DependencyIndexes: file_aiserver_v1_available_models_mvp_proto_depIdxs,
		MessageInfos:      file_aiserver_v1_available_models_mvp_proto_msgTypes,
	}.Build()
	File_aiserver_v1_available_models_mvp_proto = out.File
	file_aiserver_v1_available_models_mvp_proto_goTypes = nil
	file_aiserver_v1_available_models_mvp_proto_depIdxs = nil
}
